SonMinSeock/ikw-market

client/package-lock.json, client/package.json, client/src/pages/Login/Login.jsx
=> 카카오 로그인 기능 완료

server/models/product.js, server/models/user.js
몽고DB의 필드명 스네이크 케이스 방식으로 작성했어.ex) products_on_sale(판매 중인 상품들)
=> server:유저, 상품 모델 스키마 작성완료.

client/package.json, client/src/pages/Login/Login.jsx, package-lock.json, package.json, server/Router/root.js, server/Router/test.js, server/models/user.js, server/server.js
카카오,네이버 로그인 할때 회원가입 기능 구현했어.
유저 필드에 social_id 추가했어.
=> feat/login 카카오, 네이버 로그인 후 회원가입 기능 구현 완료.

client/src/components/atoms/Nav/Nav.tsx, client/src/pages/Login/Login.jsx, server/Router/root.js
카카오, 네이버 로그아웃 기능 구현했고, 백엔드에서 세션 유저 데이터 초기화 했어.
=> feat/login 로그아웃 기능 구현 완료

client/src/components/atoms/Nav/Nav.tsx, client/src/pages/Upload/Upload.tsx, server/Router/product.js, server/models/product.js, server/server.js
- product 모델 
- user 모델에서 products_on_sale 필드가 값이 업로드된 상품의 id 값이 있어
=> feat/upload 상품 업로드 몽고 DB 테스트 완료

client/src/components/atoms/Nav/Nav.tsx, client/src/pages/Profile/Profile.style.ts, client/src/pages/Profile/Profile.tsx
pc버전 모바일버전 두 개다 완료
약간의 패딩과 마진 prop으로 디자인 변경 예정
=> Design : 프로필 디자인 1차

client/src/components/ProductList/ProductList.tsx, client/src/components/atoms/Product/Product.tsx, server/Router/product.js
1. 상품리스트 불러오는 API 제작 완료
2. 메인 화면에서 실제 상품리스트 보여주기.
=> feat/main 메인화면 상품리스트 불러오는 기능 API 제작 완료, 실제 상품리스트 보여주기

client/src/components/atoms/Product/Product.style.ts, client/src/components/atoms/Product/Product.tsx, client/src/pages/Main/Main.style.ts, client/src/pages/ProductDetail/ProductDetail.style.ts
텍스트 넘어갔을때 줄바꿈 해주는 word-break 프로퍼티를 이용해서 break-all 값 이용 했어.
1. Product.style.ts
2. ProductDetail.style.ts
=> feat/main,upload 메인화면 상품리스트, 상품상세 페이지에서 테스트 줄바꿈 처리 코드 추가

client/src/components/Header/Header.tsx, client/src/components/ProductList/ProductList.tsx, client/src/controller/search.js, client/src/recoil/login/atoms.ts
search 컨트롤러 모듈 만들어서 문자열의 includes메서드, 배열의 filter 메서드를 이용해 검색 알고리즘 구현 했어.
- controller
┗ search.js
https://github.com/SonMinSeock/ikw-market/assets/44064257/883ed4d7-56a5-4fd3-a0a8-3c50ad567c68
=> feat/search 상품리스트 검색 기능 구현 완료

client/src/components/Header/Header.tsx, client/src/components/ProductList/ProductList.tsx, client/src/controller/search.js, client/src/recoil/login/atoms.ts
1. 입력할때 엔터키 이벤트 발생했을때 검색하도록 변경.
2. useEffect 의존성 배열을 searchText 상태값으로 추가했어.
=> feat/search 검색기능 코드 수정, 무한레더링 발생 문제 해결

client/package-lock.json, client/package.json, client/src/pages/ProductEdit/ProductEdit.tsx, client/src/recoil/login/atoms.ts, server/Router/product.js
recoil 값 새로고침해도 유지 하기위해서 recoil-persist 패키지 설치했어.
=> feat/product-edit 상품 상세페이지 라우터 보호 헤주는 코드 작성 완료

client/package-lock.json, client/package.json, client/src/pages/ProductDetail/ProductDetail.tsx, client/src/pages/ProductEdit/ProductEdit.tsx, client/src/pages/Profile/Profile.tsx, client/src/pages/Upload/Upload.tsx, client/src/recoil/login/atoms.ts, server/Router/product.js
1. 해당 상품 삭제 해주는 API 코드 작성 했어. 
2. 상품 상태 변경은  몽구스가 해당 상품 id에 변경 할 데이터를 주면 변경하니까 "/:id/update"로 통일 했어.
=> Feat/create-api 해당 상품 삭제 API, 상품 상태 변경 작업 추가

client/src/components/ProductList/ProductList.tsx, client/src/controller/sort.js, client/src/pages/Chat/Chat.tsx, client/src/pages/Main/Main.tsx, client/src/pages/ProductEdit/ProductEdit.tsx, client/src/pages/Profile/Profile.tsx, client/src/pages/Upload/Upload.tsx, client/src/recoil/login/atoms.ts
메인에서 초기 접속하면 로컬스토리지 초기화 작업을 진행.
=> 로그인 후 다시 접속할시 로그아웃 문제 이슈 해결

client/src/pages/Chat/Chat.tsx, client/src/pages/ProductEdit/ProductEdit.tsx, client/src/pages/Profile/Profile.tsx, client/src/pages/Upload/Upload.tsx
Upload, Chat, Profile, ProductEdit 컴포넌트에서 useEffect 훅을 이용해 isLogin false이면 로그인으로 리다이렉트 해주도록 만들었어.
=> feat/route-protect 수정, 마이페이지, 내 물건 팔기 업로드, 채팅 라우팅 보호 코드 추가

client/src/components/ProductList/ProductList.tsx, client/src/controller/sort.js, client/src/pages/Chat/Chat.tsx, client/src/pages/ProductEdit/ProductEdit.tsx, client/src/pages/Profile/Profile.tsx, client/src/pages/Upload/Upload.tsx
https://github.com/SonMinSeock/ikw-market/assets/44064257/1c41b1b9-a10e-446c-b6bf-fb3320428450
=> Feat/product 메인화면에서 상품리스트 최근순 및 상품완료 맨뒤 배치

client/src/App.tsx, client/src/components/atoms/Message/Message.style.ts, client/src/components/atoms/Message/Message.tsx, client/src/pages/Chat/Chat.style.ts, client/src/pages/Chat/Chat.tsx, client/src/pages/ChatList/ChatList.style.ts
추가사항
1.  Message컴포넌트 
- 채팅정보(메시지,프로필,시간) 컴포넌트
2. App.tsx 
-  모바일ver. 채팅페이지에서 스크롤 막는 함수추가
3. 소켓 연결 실패 코드 추가
=> Design : 채팅방 디자인

client/src/components/atoms/Nav/Nav.tsx, client/src/pages/ProductDetail/ProductDetail.tsx, client/src/recoil/login/atoms.ts, server/Router/chats.js, server/Router/root.js, server/lib/date.js, server/models/chat.js, server/models/user.js, server/server.js
Chat 모델 스키마.
판매자 채팅방 참여하면 판매자 유저와 소비자 유저의 chat_room 필드 추가됨.
- 소비자.
- 판매자.
- 채팅 하면 Chat 모델 만들어짐.
=> Feat/chat Chat 모델 스키마 제작 및 Chat API 중 채팅방 참여 API 제작 완료

client/src/App.tsx, client/src/components/atoms/Message/Message.tsx, client/src/components/atoms/Nav/Nav.tsx, client/src/pages/Chat/Chat.tsx, client/src/pages/ChatList/ChatList.style.ts, client/src/pages/ChatList/ChatList.tsx, client/src/pages/ProductDetail/ProductDetail.tsx, server/Router/chats.js, server/Router/root.js, server/lib/date.js, server/models/chat.js, server/server.js
1. 초기 채팅방 만들때 인사메시지 보내기
2. 한국시간 표기 모듈 수정.
3. 채팅 모델 스키마 판매자, 소비자 데이터 형식
수정.
=> Feat/chat Chat API 수정

client/src/pages/ChatList/ChatList.tsx, server/Router/chats.js, server/Router/root.js, server/models/chat.js
1. 스키마 변경 member_list에 첫번째 요소는 판매자, 두번째 요소는 소비자로 구성.
2. 상대방의 이미지, 닉네임으로 반환해주는 함수
=> feat/chat 채팅목록에서 상대방의 이미지, 닉네임으로 보여주도록 변경했음.

client/src/pages/Chat/Chat.style.ts, client/src/pages/Chat/Chat.tsx, client/src/pages/Chat/ProductInfoBar/ProductInfoBar.tsx, client/src/pages/Chat/ProductInfoBar/ProductInforBar.style.ts
상품정보바 클릭시 링크 이동하려고하는데
seller_info 에러 나옴
=> Feat : 채팅창위에 상품정보바 추가

client/src/components/atoms/Logo/Logo.style.ts, client/src/components/atoms/Product/Product.style.ts, client/src/pages/Login/Login.style.ts, client/src/pages/Main/ProductList/ProductList.style.ts
헤더, 상품리스트, 상품 컴포넌트 스타일 코드 정리 하고 조금 수정 했어.
=> Style/header 로고, 헤더 스타일 수정

client/src/App.tsx, client/src/api/userData.ts, client/src/pages/Chat/Message/Message.style.ts, client/src/pages/Chat/ProductInfoBar/ProductInfoBar.tsx, client/src/pages/Profile/Profile.tsx, client/src/pages/Profile/ProfileUpdate/ProfileUpdate.style.ts, client/src/pages/Profile/ProfileUpdate/ProfileUpdate.tsx, server/Router/profile.js, server/server.js
1. ProfileUpdate 컴포넌트 만들었어
2. 프로필 업데이트 API 제작.
3. react-query의 useMutation 훅을 이용해서 POST 요청 했어.
4. 채팅의 이미지 스타일 수정.
=> feat/profile-update ProfileUpdate 컴포넌트 생성, 프로필 닉네임 변경 API 제작.

client/src/components/atoms/Product/Product.style.ts, client/src/components/atoms/Product/Product.tsx, client/src/components/atoms/Product/Sold/Sold.style.ts, client/src/components/atoms/Product/Sold/Sold.tsx, client/src/pages/Chat/Message/Message.style.ts, client/src/pages/Main/Main.style.ts, client/src/pages/Main/ProductList/ProductList.style.ts, client/src/pages/Profile/Profile.style.ts, client/src/pages/Profile/ProfileUpdate/ProfileUpdate.style.ts
=> Style/son-product-list 상품리스트 그리드 반응형 디자인 작업 완료

client/src/components/atoms/Product/Product.style.ts, client/src/components/atoms/Product/Product.tsx, client/src/pages/Main/ProductList/ProductList.style.ts, client/src/pages/Profile/Profile.style.ts, client/src/pages/Profile/ProfileUpdate/ProfileUpdate.style.ts, client/src/pages/Profile/ProfileUpdate/ProfileUpdate.tsx
데스크탑 3열로 구성.
패드, 모바일에서 2열로 구성.
=> Design/mobile 상품리스트 레이아웃 수정 및 버튼 컨테이너 제외

client/public/index.html
=> SEO 키워드 추가
